language: go
sudo: false

go:
  - 1.9.4
  - "1.10"
  - tip

os:
  - linux
  - osx

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

script:
  - go build
  - go test -race -v ./...