// Code generated by "stringer -type=ItemState,FocusState -output=states_string.go"; DO NOT EDIT.

package data

import "fmt"

const _ItemState_name = "ItemOpenItemCompleteItemArchived"

var _ItemState_index = [...]uint8{0, 8, 20, 32}

func (i ItemState) String() string {
	if i < 0 || i >= ItemState(len(_ItemState_index)-1) {
		return fmt.Sprintf("ItemState(%d)", i)
	}
	return _ItemState_name[_ItemState_index[i]:_ItemState_index[i+1]]
}

const _FocusState_name = "FocusNoneFocusNowFocusLaterFocusWatch"

var _FocusState_index = [...]uint8{0, 9, 17, 27, 37}

func (i FocusState) String() string {
	if i < 0 || i >= FocusState(len(_FocusState_index)-1) {
		return fmt.Sprintf("FocusState(%d)", i)
	}
	return _FocusState_name[_FocusState_index[i]:_FocusState_index[i+1]]
}
